### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by umegaya** [umegaya/channer#11]
- [ ] client feature
  - [x] remove mithril js entirely
  - [ ] login/rescue/migrate device
  - [ ] create post
    - [x] rich text editor 
    - [ ] emoji
    - [ ] extra menu (post movie/photo, location, stamps)
  - [ ] FAB menus for each page
  - [ ] determine posts rendering system (displaying github comment no so bad. try 2ch and reddit)
- [ ] server feature
  - [ ] push notification
  - [ ] rewrite entire server system as actor system #4 
    - [ ] container registration, deployment system
